---
title: "00 Before Class Setup"
author: "Jillian Dunic"
date: "July 8, 2015"
output: html_document
---

Please install the following programs prior to coming to class. 

*Install R*

Mac
http://cran.r-project.org/bin/macosx/

Windows
http://cran.r-project.org/bin/windows/base/

Linux (Ubuntu)
http://cran.r-project.org/bin/linux/ubuntu/README

*Install Rstudio*

All platform downloads available here
https://www.rstudio.com/products/rstudio/download/

*Install git*

Follow the instructions here to install git on your machine
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git


If you have problems installing these programs prior to class. Please email me asap. We will have some time dedicated at the start of class to troubleshooting. For those of you who already have some experience with these programs, please assist your neighbours in class who may be having troubles.

If you are successful in setting up your computer and would like to get your feet wet in R, you can also install the package 'Swirl' and try some of the interactive tutorials. 

Follow the information at this link to start working with Swirl: http://swirlstats.com/students.html

*Terminal Tinkering*
Please attempt to play, even for 10 minutes with your terminal. This may be completely new to most of you. **

*Opening a terminal*
Mac
Type 'terminal' into spotlight


Windows Users 
**By keyboard**: 'Press "Win-R," type "cmd" and press "Enter" to open a Command Prompt session using just your keyboard.'

OR

**By mouse**: 'Click the "Start | Program Files | Accessories | Command Prompt" to open a Command Prompt session using just your mouse.'

see more detailed instructions at http://smallbusiness.chron.com/open-terminal-session-windows-7-56627.html

Now that you have a terminal open try the following commands (note you do not type the carrot '>'):

Change directory:
> cd ~

This should put you in your home directory

List the files in your directory:
> ls -a

Change directory:
> cd type_directory_name_or_path_here

Get the path to your current directory:
> pwd

Go back to the directory one level up:
> cd ..


More commands can be found here if you are interested in learning more. But for now I just want you to have some exposure. Note - a directory is just a folder. 
http://cli.learncodethehardway.org/book/ex1.html

**If you struggle to open a terminal. Follow the instructions here: http://cli.learncodethehardway.org/book/ex1.html











