---
title: "Pre-Class Setup"
output: html_document
---
\  

### Please install the following programs prior to coming to class.  
\  

#### 1) Install R
OS              | R                                            |
--------------- | -------------------------------------------- |
Mac             | http://cran.r-project.org/bin/macosx/        |
Windows         | http://cran.r-project.org/bin/windows/base/  |
Linux (Ubuntu)  | https://cran.r-project.org/bin/linux/ubuntu/ |

  
#### 2) Install Rstudio

All platform downloads available here
https://www.rstudio.com/products/rstudio/download/  
\  

#### 3) Install git

##### Mac
Get the latest version of git here:  
http://git-scm.com/downloads  
This should work 'out of the box' but if not contact me asap.
\  

##### Windows 
Download git for Windows from here and run the installer.
https://git-for-windows.github.io/
\  

##### Linux
You will most likely use your standard package-manager 

Debian-based/Ubuntu:
sudo apt-get install git
\  
Fedora:
sudo yum install git
\  

#### 4) Create a Github account and request an education account

Please create an account even if you cannot install git on your local computer.
https://github.com/
\  

Request an education discount! You get free stuff! I recommend requesting your educational discount now, as these take time to process. 
https://education.github.com/discount_requests/new
\  

#### Special Note for Windows users
Because I want to introduce the shell/terminal/command line, you will need to install Cygwin, a Unix-like command line interface. 

Because I want to introduce you to using the terminal, we will need to install Cygwin, a Unix-like command line interface. This 

If you have problems installing these programs prior to class. Please email me asap. We will have some time dedicated at the start of class to troubleshooting. For those of you who already have some experience with these programs, please assist your neighbours in class who may be having troubles.

If you are successful in setting up your computer and would like to get your feet wet in R, you can also install the package 'Swirl' and try some of the interactive tutorials. 

Follow the information at this link to start working with Swirl: http://swirlstats.com/students.html


------------------------------------------------------------------------------------------

*Terminal Tinkering -- for Mac and Linux users only*
Please attempt to play, even for 10 minutes with your terminal. This may be completely new to most of you. **

*Opening a terminal*
Mac
Type 'terminal' into spotlight

Now that you have a terminal open try the following commands (note you do not type the carrot '>'):

Change directory:
> cd ~

This should put you in your home directory

List the files in your directory:
> ls -a

Change directory:
> cd type_directory_name_or_path_here

Get the path to your current directory:
> pwd

Go back to the directory one level up:
> cd ..


More commands can be found here if you are interested in learning more. But for now I just want you to have some exposure. Note - a directory is just a folder. 
http://cli.learncodethehardway.org/book/ex1.html












